apiVersion: apps/v1
kind: Deployment
metadata:
  name: legal-dms-frontend
  namespace: legal-dms
  labels:
    app: legal-dms
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: legal-dms
      component: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: legal-dms
        component: frontend
    spec:
      serviceAccountName: legal-dms-frontend
      securityContext:
        runAsUser: 101  # nginx non-root user
        runAsGroup: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: frontend
        image: ${DOCKER_REGISTRY}/legal-dms-frontend:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: legal-dms-config
              key: api-url
        - name: REACT_APP_AUTH_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: legal-dms-config
              key: auth-timeout
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run
      volumes:
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}
      imagePullSecrets:
      - name: docker-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: legal-dms-frontend
  namespace: legal-dms
  labels:
    app: legal-dms
    component: frontend
spec:
  selector:
    app: legal-dms
    component: frontend
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: legal-dms-frontend-hpa
  namespace: legal-dms
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: legal-dms-frontend
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70